### ISSUE TITLE
The bBuggy issue

### ISSUE THREAD

**Issue by HasnatPranto** [ahmedryan/Skin-Detection_Naive-Bayes#1]
![rdebug](https://user-images.githubusercontent.com/43754044/101057641-751bac80-35b6-11eb-97fb-8c166800b672.PNG)

Think this _**static**_ keyword in ConfusionMatrix.java is causing all the chaos here, pls do check

**Comment by ahmedryan** [comment]
> ![rdebug](https://user-images.githubusercontent.com/43754044/101057641-751bac80-35b6-11eb-97fb-8c166800b672.PNG)
> 
> Think this _**static**_ keyword in ConfusionMatrix.java is causing all the chaos here, pls do check
